package com.redshift.rasr.oauth.data;
// Generated Nov 13, 2015 3:37:25 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private Integer id;
	private String clientId;
	private String clientSecret;
	private Set tokenses = new HashSet(0);

	public Client() {
	}

	public Client(String clientId, String clientSecret) {
		this.clientId = clientId;
		this.clientSecret = clientSecret;
	}

	public Client(String clientId, String clientSecret, Set tokenses) {
		this.clientId = clientId;
		this.clientSecret = clientSecret;
		this.tokenses = tokenses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	public String getClientSecret() {
		return this.clientSecret;
	}

	public void setClientSecret(String clientSecret) {
		this.clientSecret = clientSecret;
	}

	public Set getTokenses() {
		return this.tokenses;
	}

	public void setTokenses(Set tokenses) {
		this.tokenses = tokenses;
	}

}
