package com.redshift.rasr.oauth.data;
// Generated Dec 23, 2015 1:35:17 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private Integer id;
	private String clientId;
	private String clientSecret;
	private Set clientNodes = new HashSet(0);
	private Set tokens = new HashSet(0);

	public Client() {
	}

	public Client(String clientId, String clientSecret) {
		this.clientId = clientId;
		this.clientSecret = clientSecret;
	}

	public Client(String clientId, String clientSecret, Set clientNodes, Set tokens) {
		this.clientId = clientId;
		this.clientSecret = clientSecret;
		this.clientNodes = clientNodes;
		this.tokens = tokens;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	public String getClientSecret() {
		return this.clientSecret;
	}

	public void setClientSecret(String clientSecret) {
		this.clientSecret = clientSecret;
	}

	public Set getClientNodes() {
		return this.clientNodes;
	}

	public void setClientNodes(Set clientNodes) {
		this.clientNodes = clientNodes;
	}

	public Set getTokens() {
		return this.tokens;
	}

	public void setTokens(Set tokens) {
		this.tokens = tokens;
	}

}
