package com.redshift.rasr.oauth.data;
// Generated Dec 23, 2015 1:35:17 PM by Hibernate Tools 4.3.1.Final

/**
 * ClientNode generated by hbm2java
 */
public class ClientNode implements java.io.Serializable {

	private Integer id;
	private Client client;
	private Node node;

	public ClientNode() {
	}

	public ClientNode(Client client, Node node) {
		this.client = client;
		this.node = node;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Node getNode() {
		return this.node;
	}

	public void setNode(Node node) {
		this.node = node;
	}

}
