package com.redshift.rasr.oauth.data;
// Generated Dec 23, 2015 1:35:17 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Node generated by hbm2java
 */
public class Node implements java.io.Serializable {

	private Integer id;
	private int nodeId;
	private Set clientNodes = new HashSet(0);

	public Node() {
	}

	public Node(int nodeId) {
		this.nodeId = nodeId;
	}

	public Node(int nodeId, Set clientNodes) {
		this.nodeId = nodeId;
		this.clientNodes = clientNodes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getNodeId() {
		return this.nodeId;
	}

	public void setNodeId(int nodeId) {
		this.nodeId = nodeId;
	}

	public Set getClientNodes() {
		return this.clientNodes;
	}

	public void setClientNodes(Set clientNodes) {
		this.clientNodes = clientNodes;
	}

}
