package com.redshift.rasr.oauth.data;
// Generated Nov 13, 2015 3:37:25 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Tokens generated by hbm2java
 */
public class Tokens implements java.io.Serializable {

	private Integer id;
	private Client client;
	private String token;
	private Date expires;
	private String authorizationServer;

	public Tokens() {
	}

	public Tokens(Client client, String token, Date expires) {
		this.client = client;
		this.token = token;
		this.expires = expires;
	}

	public Tokens(Client client, String token, Date expires, String authorizationServer) {
		this.client = client;
		this.token = token;
		this.expires = expires;
		this.authorizationServer = authorizationServer;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public Date getExpires() {
		return this.expires;
	}

	public void setExpires(Date expires) {
		this.expires = expires;
	}

	public String getAuthorizationServer() {
		return this.authorizationServer;
	}

	public void setAuthorizationServer(String authorizationServer) {
		this.authorizationServer = authorizationServer;
	}

}
